#!/usr/bin/env node

const fs = require('fs');
const { exec } = require("child_process");
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
  terminal: false
});

console.log('Content-type: application/json');
console.log('');

const lines = [];
rl.on('line', (line) => lines.push( line ) );
rl.on('close',  () => {
    const input = lines.join();
    const data = JSON.parse(input);
    const conf = [];

    conf.push('    <Location />');
    for(const ip of data) {
        conf.push(`        Require ip  ${ip}`);
    }
    conf.push('    </Location>');
    conf.push('');

    fs.writeFile('conf.fs',conf.join('\n'),(err) => {

        if(err)
            console.log(err);
        else {

            exec("apachectl configtest", (error, stdout, stderr) => {

                console.log({error, stdout, stderr});
            });
        }
    });   
});

ls 