#!/usr/bin/bash 

CONF=ips.conf

echo "    <Location />" > $CONF
while read line
do
  echo "        Require ip $line" >> $CONF
done < "${1:-/dev/stdin}"
echo "    </Location>" >> $CONF

OUT=`apachectl configtest 2>&1` 

echo "Content-type: text/plain"
echo ""
echo $OUT


